[theme]
base = "dark"
primaryColor = "#8AB4F8"
backgroundColor = "#202124"
secondaryBackgroundColor = "#303134"
textColor = "#E8EAED"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
